# Generated by Django 5.2.15 on 2026-09-05 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(blank=True, max_length=150)),
                ('difficulty', models.CharField(default='intermediate', max_length=50)),
                ('is_remediation', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=0)),
                ('percentage', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('primary_hazards', models.TextField(blank=True, help_text='Comma-separated major hazards')),
            ],
        ),
        migrations.CreateModel(
            name='SafetyTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('sop_code', models.CharField(max_length=20)),
                ('sop_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='shield', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.CharField(max_length=50)),
                ('scenario_context', models.TextField(blank=True)),
                ('question_text', models.TextField()),
                ('chosen_option', models.CharField(max_length=10)),
                ('chosen_text', models.TextField()),
                ('correct_option', models.CharField(max_length=10)),
                ('correct_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('explanation', models.TextField()),
                ('consequence', models.TextField()),
                ('sop_reference', models.CharField(blank=True, max_length=150)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='safety_app.assessmentattempt')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='safety_app.department')),
            ],
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='safety_app.employee'),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='safety_app.safetytopic'),
        ),
    ]
